adminpages/approvals.php, pmpro-approvals.php
Setup for PMPro Approvals Add-on
=> First Pull Request (Initial Setup)

adminpages/approvals.php, pmpro-approvals.php
Move Approve/Deny/ResetMember into relevant methods
=> Move Approve/Deny/ResetMember into relevant methods

adminpages/approvals.php, pmpro-approvals.php
Added:
Content filter
Adjust content filter message if user does not have approval.
=> Content filter + Message

adminpages/approvals.php, adminpages/userinfo.php, pmpro-approvals.php
Added the following -
* Read-only profile link
* Read-only profile information (Membership status, approval status, general information)
* Back to approvals button in read-only profile
=> Enhancements

adminpages/userinfo.php, pmpro-approvals.php
* Allow admin to approve/deny member form viewing their readonly profile
* Fixed errors for membership status, changed to membership level
* Fixed error for displaying the users approval status.
=> Minor fixes + Readonly Profile

adminpages/userinfo.php, pmpro-approvals.php
Added:
- Display user status on account / confirmation page for Paid Memberships Pro
- Helper function created to get a users approval status (returns 'approved', 'denied' or 'pending')
=> Helper function for user status

adminpages/userinfo.php, email/admin_approved.html, email/admin_denied.html, email/admin_notification.html, email/application_denied.html, pmpro-approvals.php
*Added email notifications for approve/deny for admins and users.
* Filter added to adjust admin email address to be added
* Email admin when user signup for approval required membership.
=> Email notifications all round

pmpro-approvals.php
Approve / Deny members from within the edit user profile.
=> Edit user profile

email/application_approved.html
Added HTML email template for Approved
=> Approved email html

pmpro-approvals.php
Adjust the text to show that the user is pending in their confirmation
email.
=> Adjust confirmation email text.

pmpro-approvals.php
* Added user log to ‘edit user page’
* Added notification to admin bar and admin menu when there is a user
pending.
=> User Log + Notifications

pmpro-approvals.php
Update Dev branch with Master.
=> Need to filter pmproet_templates before init.

adminpages/userinfo.php
Bug Fix: Show custom fields in the 'view' page for pending members.
=> Bug Fix: Show Custom Fields In View Page

pmpro-approvals.php
Adding filters for the is[Approved|Denied|Pending]() class methods (allow 3rd party code to override the status if needed)
=> ENHANCEMENT: Add filters for access test methods

pmpro-approvals.php
* Refactor: Changed the menu code slightly to make it more optimal.
* Enhancement: Support PMPro 2.0 menu structure, thanks to - @ioamnesia (https://github.com/ioamnesia)
* Bug Fix: Approvals notification icon wouldn't show orange background when on frontend of your site in the admin menu bar.
=> Enhancement: Tidy up menu code for V2.x

classes/class.approvalemails.php, email/admin_approved.html, email/admin_denied.html, email/admin_notification.html, email/application_approved.html, pmpro-approvals.php
* Bug Fix: Wrong username passed through when Email Templates Admin Editor.
* Enhancement: Refactor code regarding email and put into it's own class which extends the PMProEmail class.
* Enhancement: Better wording for email templates.
* Enhancement: Included additional variables for admin_* emails such as !!view_profile!!, !!approve_link!!, !!deny_link!! and !!member_name!!.
* Updated email template name for 'admin_notification_approval' from 'admin_notification_approved' (This may have caused some confusion as this is for the pending email sent to admins and not the admin approved email template).
* Enhancement: Loaded better body content when the email templates admin editor is used.
=> Improve email system.

adminpages/approvals.php, adminpages/userinfo.php, pmpro-approvals.php
Bug Fix: User's would show approved if their email was not confirmed.
=> Email Confirmation Integration

pmpro-approvals.php, readme.txt
=> Update version + readme.

pmpro-approvals.php
Email Confirmation message fix.
=> Email Confirmation Message Fix

pmpro-approvals.php
Bug Fix: pending status shown for old members list.
=> Bug Fix: Pending status shows up for old members

classes/class.approvalemails.php
add !!member_email!! to custom variables
=> Update Email variables

classes/class.approvalemails.php, pmpro-approvals.php
Remove membership_id and membership_level variable from admin
=> Remove membership_id variable from admin

adminpages/approvals.php
Enhancement: added in actions for the Approvals table.
* pmpro_approvals_list_extra_cols_header
* pmpro_approvals_list_extra_cols_body
Fixes issue: https://github.com/strangerstudios/pmpro-approvals/issues/59
=> Enhancement: Add in filters for approvals table

adminpages/userinfo.php
Bug Fix: Register Helper Fields that had stored information as an array such as a multi select field would throw an error when viewing pending members.
=> Bug Fix: Support Array type of fields

.github/CONTRIBUTING.md, .github/ISSUE_TEMPLATE.MD, .github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/enhancement.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/support.md, .github/PULL_REQUEST_TEMPLATE.MD
Added Github templates like core.
=> Added Github Templates

pmpro-approvals.php
Enhancement: Automatically hide non approved members from directory page.
NOTE: This requires Membership Directory .5.3 to work.
Closes Issue: https://github.com/strangerstudios/pmpro-approvals/issues/48
1. This requires a future release of Member Directory (.5.3)
2. All pending/denied (not approved) members won't show up in member directory page.
Enhancement: Hide non-approved members from Member Directory Add On.
=> Integrate with Member Directory

classes/class.approvalemails.php
Fix view_profile placeholder link
1. Have a user check out for level requiring approval
2. Verify that profile link in email works
=> Fixed view_profile placeholder link

adminpages/userinfo.php
Enhancement: Edit user button for the 'viewinfo' page.
Improved escaping.
Closes Issue: N/A.
1. Navigate to "Approvals" and click on "View" user link.
2. This now adds in a button that will allow admins to get to the edit user page easier.
* Enhancement: Added in a button that redirects admins/moderators to edit the user from the Approvals view info page.
=> Enhancement: Added Edit User Button

pmpro-approvals.php, readme.txt
Version bump and changelog update.
=> Update readme version

classes/class.approvalemails.php, readme.txt
=> Update master to 1.3.1

pmpro-approvals.php, readme.txt
=> Update master to V1.3.4

adminpages/approvals.php
Closes Issue: #115 .
1. Hook into the action `pmpro_approvals_list_extra_cols_body`. You'll now get a variable with values and not a NULL value
> Undefined variable fixed when using the pmpro_approvals_list_extra_cols_body hook
=> Fixed Undefined Variable

pmpro-approvals.php
Adds a force param for approvals and a filter to prevent sending emails.
Closes #134
See gist: https://gist.github.com/ronalfy/9298cc44393127b0a26a900912d2bf4e
Add a force parameter to static method approveMember to skip permission checks for programmatically approving a member.
=> Add Force Param to approveMember

pmpro-approvals.php
This pull request adds 4 new filters that enable developers to control the Add On's admin output data:
-  `pmpro_approvals_pending_approvals_sql_parts` that filters SQL parts
for the query to fetch all users pending approval.
- `pmpro_approvals_pending_approvals_sql` that filters the final SQL string
for the query to fetch all users pending approval.
- `pmpro_approvals_approval_count_sql_parts` that filters SQL parts
for the query to get pending approvals count.
- `pmpro_approvals_approval_count_sql` that filters  SQL string
for the query to get pending approvals count.
Closes Issue: #123.
Use any of the new filters to influence the approvals count or the list of users needing approval
e.g
```php
<?php
function mypmpro_approvals_pending_approvals_sql_parts(
$sql_parts,
$l,
$s,
$status, …
```
=> Add admin page SQL filters

pmpro-approvals.php
ENHANCEMENT: Clean up data if a user is pending and changes or cancels their membership level.
=> ENHANCEMENT: Clear approval data when pending and cancelled.

adminpages/userinfo.php
continue looping through fields after checking a field that is not for that level.
Closes Issue: XXX.
1.
2.
3.
=> continue looping through fields

pmpro-approvals.php
If an admin clicks the "X" link from the approvals page or edit user page, this runs the resetMember method to set the member back in pending status. However, for some reason we weren't capturing the current_user info like we are for the approve/deny methods. This PR fixes that.
1. Approve a member.
2. Click the X to reset their approval.
3. Note that the approval log shows who set the approval to pending.
=> Remember who reset the approval.

pmpro-approvals.php
Fixes an error that occurs on the Approvals page when there are no approvals pending.
1. Visit the Approvals page and ensure that there are no approvals pending
2. No error should be shown.
> Fixed an error that was thrown when counting approvals
=> Fixes approval count error when count is 0

pmpro-approvals.php
Updated esc_html to include underscores so the text could be translated.
=> Fix esc_html code to work to translat line

adminpages/userinfo.php
* Support User Fields logic instead of Register Helper.
=> Support User Fields

classes/class.approvalemails.php, pmpro-approvals.php
Updates getOption to get_option and prefixes accordingly
=> Updates getOption to get_option
