pmpro-approvals.php
Fixed an issue where the text would display text for ‘membership is
pending’ even if the user is a guest/not-logged in or had a membership
that doesn’t require approval.
=> Text filter non members

pmpro-approvals.php
Sloppy lookup for of member variable in level object (should be `allow_signups` and not `hidden`, shouldn't it???)
=> BUG FIX: Didn't check if level var exists

pmpro-approvals.php
Bug Fix: `[membership level="0"] Show for non-members.  [/membership]` would be hidden for logged-in non-members.
This checks to see if the user has a level before continuing on the Approvals restriction.
=> Membership Shortcode Fix

pmpro-approvals.php
This adds a filter to the approval status text. This is useful for other plugins to hook into (such as email confirmation add on) and change the message from "Approved" to "Waiting for Email Confirmation".
This does not affect the approved, pending or denied status but simply changes the wording.
=> Add Filter to Approval Status text

classes/class.approvalemails.php
In some cases the admin details would be set to the user's instead.
This forces to use the admin email address in the "Settings" > "General" area.
=> Bug Fix: Admin email details were incorrect.

pmpro-approvals.php
Bug Fix: If a user didn't have a membership level it would still try to get the level object from the approvals screen.
=> Bug Fix: Property of undefined

pmpro-approvals.php
Bug Fix: Remove the 'status' bullet point if the membership level doesn't require approval.
=> Remove 'Status' from account page.

pmpro-approvals.php
Change your level to a different status.
Adjusts the "Your Level" text if the user is pending or denied.
Closes Issue: https://github.com/strangerstudios/pmpro-approvals/issues/53.
1. Sign up for a level which requires approval. Do not approve this user.
2. View levels page. Your level should change to "Pending Approval".
3. Deny the user. Go back to levels page, Your level should change to "Membership Denied".
Enhancement: Change "Your Level" text on levels page, and all instances to "Pending Approval" or "Memberships Denied" if not approved.
=> Change "Your Level" to a different status

adminpages/userinfo.php, classes/class.approvalemails.php, pmpro-approvals.php, readme.txt
Bug Fix: Email URLs for some email templates were 404.
Minor bug fix in i18n for account bullet top.
Bug Fix: URL for the 'who' approved was being escaped in the view profile for Approvals "View Info" page.
Version bump + readme adjustment.
Closes Issue: XXX.
1.
2.
3.
=> Bug Fixes + Version Bump

pmpro-approvals.php
Allow user's to update their custom fields if not-approved in the edit user profile page.
Closes Issue: N/A
1. Edit a non-approved user which has custom fields from Register Helper.
* Bug Fix: Custom fields not showing up on edit user profile page for non-approved members.
=> Allow users to update profile fields

pmpro-approvals.php
BUG FIX: Approval status in member list fix.
Closes Issue: https://github.com/strangerstudios/pmpro-approvals/issues/95.
1. Create some pending members.
2. View the Member's List for PMPro.
BUG FIX: Approval status not showing under users inside the Member's List.
=> BUG FIX: Approval Status in Member List

pmpro-approvals.php
In PMPro_Approvals::pmpro_has_membership_level(), we check for is_admin() before calling get_current_screen(). However, "there are cases where is_admin() will return true, but attempting to call get_current_screen() will result in a fatal error because it is not defined. One known example is wp-admin/customize.php." (from the WP Codex: https://codex.wordpress.org/Function_Reference/get_current_screen) Updating to also check if get_current_screen() is defined to avoid fatal errors.
Forum ticket (mods only): 
https://www.paidmembershipspro.com/forums/topic/aprovals/
Checking if 'get_current_screen' is defined to prevent errors when checking membership access from admin.
=> Fix for get_current_screen undefined error

pmpro-approvals.php
Closes Issue: XXX.
1. Activate pmpro-approvals
2. Activate pmpro-member-directory
3. Change database prefix to anything but wp_
There is a problem with WP installations that use a different DB prefix and the LEFT JOIN had the default wp_ prefix and the JOIN didn't run correctly.
=> Fix hardcoded database prefix

pmpro-approvals.php
Add filter to requiresApproval to allow it to be modified on an ad hoc basis (e.g., in certain renewal situations). Unfiltered (stock) code flow is unchanged.
=> Add filter to requiresApproval

pmpro-approvals.php
For sites using "Pay by Check" as the primary gateway, the confirmation message was not including the check payment instructions as in the core PMPro plugin. This PR adds that back to the filtered message.
* BUG FIX/ENHANCEMENT: Now showing the payment instructions for the Pay by Check payment gateway as part of the Membership Confirmation message for any level that requires approval.
=> Adding Check gateway payment instuctions to filtered confirmation message text.

pmpro-approvals.php
There was an issue in the previous PR for the check payment instructions - a warning when the level is free because the $pmpro_order object is "FALSE" in this case.
This PR checks that the $pmpro_order object is not empty on the confirmation page.
=> Fixing a notice for check payment instructions confirmation message text when approval level is free

classes/class.approvalemails.php
#113 Trying to get property of non-object when emails are sent - Fixed
Closes Issue: #113.
1. Set the site's email notification address to an email address that doesn't match any users.
2. The plugin will then try and get a user by that email. Returns false. Notices are thrown. 
=> PHP Notice Fixed

adminpages/userinfo.php
BUG FIX: Fixed an issue where multiple fields belonging to different levels with the same name would show up twice on the view info page of the approvals. This now supports the 'level' attribute inside Register Helper when displaying fields.
=> Bug Fix: Support Register Helper better

pmpro-approvals.php
This request includes a function virtually identical to the "requiresApproval" method that allows filters to be applied to the "requires_approval" option, except that filters are applied to the "restrict_checkout" option. This has specific value for the checkout page that restricts users from checking out if another level requires approval.
This has specific application for the need to automatically approve members that were previously approved but their membership has since lapsed. 
Does not close, but helps address issue: #117 
1. Create a new filter, `add_filter( 'pmpro_approvals_level_restrict_checkout', 'approve_previous_members', 10, 2 );`
2. Have it return false (for testing).
3. Notice that now on the checkout page, the user will always be approved for their membership …
=> Added a filter for the restrict checkout option

classes/class.approvalemails.php
Add `$level` variable to the `pmpro_approvals_member_denied_email_data` filter as what the approved email data filter has to allow obtaining level-specific data that may be useful when creating custom email template variables depending on data in the level object.
=> add level variable to  denied data filter

readme.txt
Removing the recommendation to edit emails via the Add On - this is now a feature of core PMPro.
=> Adjusting the readme to recommend email edits via core PMPro v2.6+ admin page.

pmpro-approvals.php
Fixed bug where if a user was pending for a level and they checked out for the level again, the "pending" flag would be removed from their membership and they would be considered to be approved.
=> Fix bug where checking out for same level would approve user.

pmpro-approvals.php
The redesign of the Membership Levels page + templates are slated for PMPro v2.9. We are including Approvals in the template list. This PR updates the Approval Settings section to match the v2.9+ format for the levels admin page.
v2.9 adds new hooks so that Add Ons like this can place their settings in more places on the edit page. I have conditionally used the new hook to show this box right below the general settings of that new UI.
For sites that are not on 2.9, the settings section will be shown as it is today at the bottom of the page.
Note that the appearance is a bit less than perfect since the new format relies on CSS in core PMPro v2.9+. I think rather than replicate this formatting or code to variations of the section we add based on PMPro version we just live with this less …
=> Level template and new section for level add/edit page for PMPro v2.9+

adminpages/approvals.php, adminpages/userinfo.php, classes/class.approvalemails.php, pmpro-approvals.php
Add compatibility with PMPro Multiple Memberships Per User. Note that this does not include compatibility for purchasing multiple levels in a single checkout, only for managing users who have multiple levels.
Specific changes made include:
- Fixing the Approvals Admin page
- Updating emails to pull information about the specific level being approved/denied
- Updating Account page to show approval status for all approval levels that the user has
- Updating functions  with `level` as an optional parameter to throw a "doing it wrong" warning
- Removing approving/denying users directly from the edit user page. Instead, now shows a link to the approvals admin page
- Removed code that shows "pending" and "denied" levels on the Levels page. This would be nice to add back, but it is not currently …
=> Added MMPU compatibility

pmpro-approvals.php
* BUG FIX: Fixed a warning when the approval count value was 0 and results were empty.
=> Warning fix for 0 approvals.

pmpro-approvals.php
Updating the "no access" message UI for PMPro v3.1 and avoiding deprecated filters.
=> Updating the "no access" message for 3.1

pmpro-approvals.php
* ENHANCEMENT: Added the filter `pmpro_approvals_show_confirmation_message` which allows you to show the custom levels confirmation message. Defaults to false.
Resolves: https://github.com/strangerstudios/pmpro-approvals/issues/173
=> Added filter to show custom confirmation message.

classes/class.approvalemails.php
> Resolve PHP warnings that can occur when the site administrator email isn't associated with a WordPress user account
=> Fix admin email PHP warnings

pmpro-approvals.php
Fixes conflict with Pay By Check if user fields are restricted by level.
Previously, these user fields would not be saved when an admin changes the order from `pending` to `success`.
=> Always use the user's real levels in the admin

pmpro-approvals.php
Need to be merged taking into consideration this one -> https://github.com/strangerstudios/paid-memberships-pro/pull/3322
Remove hook to deprecated `pmpro_member_shortcode_access` filter
* Deprecate filter callback function `pmpro_member_shortcode_access`
* Restore `_doing_it_wrong` function call removed in a previous commit.
* Add several unhandled cases to `pmpro_has_membership_level` filter callback and removed not safe checks to better handle empty levels and other cases.
1. Add a membership short code without a level to a page. [membership] some content [/membership]
2. Without this patch, you'll see and error in debug.log  with message `You should pass a level ID to getUserApproval.`
3. With the patch, the deprecated hook won't call getUserApproval then wont throw the error.
4. It's …
=> Fixing pmpro_has_membership_level() without specifying level (and other edge cases)

pmpro-approvals.php
Added a check to confirm that we have a level object to ensure the level name attribute is available when we create an approval status message.
Closes Issue: #187
1. Enable WP Debug and debug display.
2. Check out for a level that requires approval.
3. As admin, delete that level.
4. Return to the Membership Account page for the user that needed approval.
5. Confirm that the message reported in issue [#187](https://github.com/strangerstudios/pmpro-approvals/issues/187) is no longer displayed.
=> add a check to confirm we have a level object.

adminpages/approvals.php, pmpro-approvals.php
Prevents database errors that occur on Approvals admin pages when no levels require approval.
Some WPCS changes.
Closes: #202
1. Enable error logging.
2. Ensure none of your levels require approval.
3. Visit Approvals admin pages.
4. Observe that no database errors are logged.
=> Fix for database errors that occur if no levels require approval

classes/email-templates/class-pmpro-email-template-pmpro-approvals-admin-approved.php, classes/email-templates/class-pmpro-email-template-pmpro-approvals-admin-denied.php, classes/email-templates/class-pmpro-email-template-pmpro-approvals-admin-notification-approval.php
Add `_admin` suffix to the admin email template keys. 
Resolves #205 
1. Navigate to _Memberships > Settings > Email Templates_.
2. Check the _Default Recipient_ column values for the _Approval Approved (admin)_, _Approval Denied (admin)_, and _Approval Pending (admin)_ email templates.
> Fixed incorrect recipient labels on the Email Templates admin screen.
=> Fix Default Recipient label for admin emails

pmpro-approvals.php
* BUG FIX: Fixed an issue where Directory pages would not be restricted if pending approval or denied.
Resolves: https://github.com/strangerstudios/pmpro-approvals/issues/211
Prior to this logic, we assumed that all generated PMPro pages should be accessible even if denied or awaiting approval which makes sense for the default PMPro pages generated by core. However, the Membership Directory and Profile pages are often premium features for members to access and view which is why this change has been made to always honor content restriction for the directory and profile pages.
=> Restrict Member Directory and Profile when pending
